### ISSUE TITLE
access denied error

### ISSUE THREAD

**Issue by pramod2804** [tenable/integrations-aws-ct#1]
Getting access denied for https://tenable-connectors.s3.amazonaws.com/cloud-templates/aws/Tenable-Connector-CloudFormation.json

**Comment by tenableChris** [comment]
I believe we restored that file about two weeks ago.

**Comment by Dlozitskiy** [comment]
Is there anyone at Tenable.io who can fix this to reflect what's written in the guide https://d1.awsstatic.com/Marketplace/solutions-center/downloads/Tenable-Nework-Security-AWS-ControlTower-Implementation-guide.pdf?

The template https://github.com/tenable/integrations-aws-ct/blob/master/tenable-control-tower-cfn.yml has a resource for a CFN stack with parameters that don't existing in the template https://tenable-connectors.s3.amazonaws.com/cloud-templates/aws/Tenable-Connector-CloudFormation.json which is causing deployment to fail.

```
  TenableConnectorRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PrincipalAws: arn:aws:iam::012615275169:root <<<<<<<<<<<<< Doesn't exist in the template below
        RoleName: tenableio-connector <<<<<<<<<<<<< Doesn't exist in the template below
        TenableExternalId: !Ref externalId <<<<<<<<<<<<< Doesn't exist in the template below
      TemplateURL: https://tenable-connectors.s3.amazonaws.com/cloud-templates/aws/Tenable-Connector-CloudFormation.json
```
